name: Deploy static content to Hexo

on:
  push:
    branches: ["code"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  blog-jinglun:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write # 确保有写权限
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'  # 使用较新版本的 Node.js

      # - name: Install hexo dependencies
      #   run: |
      #     npm install -g hexo-cli
      #     npm install

      # - name: Generate files
      #   run: |
      #     hexo clean
      #     hexo generate

      - name: Build and Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.HEXO_TOKEN }}  # GitHub Token
          publish_dir: ./public                      # Hexo 生成的文件夹
          publish_branch: master                     # 要推送的分支
          external_repository: chinalijinglun/chinalijinglun.github.io # 目标仓库
